// <auto-generated />
using System;
using System.Collections.Generic;
using LuxeLooks.DataManagment;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuxeLooks.DataManagment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuxeLooks.Domain.Entity.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<List<Guid>>("ProductsIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LuxeLooks.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsForKids")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsForMen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42b4e367-16a8-4a03-ba3f-d729c2535a86"),
                            Description = "Super baggy fit jeans with a five-pocket design, belt loops, and a zip fly and top button fastening. Made from 100% cotton",
                            ImageUrl = "https://static.pullandbear.net/2/photos//2023/I/0/2/p/7688/526/427/03/7688526427_2_6_8.jpg?t=1689251224432&imwidth=850",
                            IsForKids = false,
                            IsForMen = true,
                            Name = "SUPER BAGGY JEANS",
                            Price = 129m,
                            Type = 10
                        },
                        new
                        {
                            Id = new Guid("7b23b319-6d1d-4317-abd4-76e9a64ea7fa"),
                            Description = "Flat Mary Jane shoes. Available in several colours. Patent effect. Chunky sole. Buckled front strap.",
                            ImageUrl = "https://static.pullandbear.net/2/photos//2023/I/1/1/p/1473/240/022/1473240022_2_1_8.jpg?t=1692269215615&imwidth=375",
                            IsForKids = false,
                            IsForMen = false,
                            Name = "CHUNKY SOLE FLAT SHOES",
                            Price = 149m,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("7c7b8cf9-1212-42fa-8b67-637464359062"),
                            Description = "Oversized fit wide-leg low-rise baggy jeans with a five-pocket design, belt loops, a zip fly and top button fastening and faded details. Made from cotton.",
                            ImageUrl = "https://static.pullandbear.net/2/photos//2023/I/0/1/p/7688/309/427/7688309427_2_1_8.jpg?t=1691508453560&imwidth=375",
                            IsForKids = false,
                            IsForMen = false,
                            Name = "ДЖИНСЫ ОВЕРСАЙЗ СВОБОДНОГО КРОЯ",
                            Price = 129m,
                            Type = 10
                        },
                        new
                        {
                            Id = new Guid("03ced595-265e-495a-b123-d371c0d46c24"),
                            Description = "Стильная куртка для мальчика из коллекции OUTERWEAR BOY JUNIOR станет идеальным выбором для повседневного отдыхам в холодное время года. Мембранная куртка оснащена флисовой подкладкой, светоотражающими элементами икарманами для любимых мелочей. Рукава отделаны эластичной манжетой, которая сохранит тепло в холодное время года.",
                            ImageUrl = "https://buslik.by/upload/resize_cache/iblock/a17/486_568_1/ld3wu2gwzmuhvkb6i1uam369xu4n5ow6.jpg",
                            IsForKids = true,
                            IsForMen = true,
                            Name = "Куртка для мальчика OUTERWEAR BOY JUNIOR",
                            Price = 104.9m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("LuxeLooks.Domain.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44546e06-8719-4ad8-b88a-f271ae9d6eab"),
                            NormalizedRoleName = "ADMIN",
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("44546e06-8719-4ad8-b88a-f271ae9d6abe"),
                            NormalizedRoleName = "RESIDENT",
                            RoleName = "Resident"
                        });
                });

            modelBuilder.Entity("LuxeLooks.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b161353-2e3d-4b54-821e-4c6f34cefd31"),
                            Email = "alsemkovbn@gmail.com",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "$2a$12$iW6RyEqQv.ZON5f.ipkDxeyYfa9OJhRNqAPLZ1GomhuU6NfU/l/Bu",
                            PasswordSalt = "$2a$12$iW6RyEqQv.ZON5f.ipkDxe",
                            RefreshTokenExpiryTime = new DateTime(2023, 9, 28, 12, 12, 24, 40, DateTimeKind.Utc).AddTicks(9292),
                            RoleId = new Guid("44546e06-8719-4ad8-b88a-f271ae9d6abe"),
                            UserName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
