@startuml
scale 450 width

[*] --> Авторизован

state Авторизован {
  [*] --> Ожидание
  Ожидание --> ДобавлениеТовара : Добавить товар в корзину
  ДобавлениеТовара --> Ожидание : Товар успешно добавлен
}

@enduml
