@startuml
scale 350 width

[*] --> Авторизован

state Авторизован {
  [*] --> Ожидание
  Ожидание --> ЗаполнениеДанных : Нажатие "Оформить заказ"
  ЗаполнениеДанных --> ПодтверждениеЗаказа : Заполнение данных заказа
  ПодтверждениеЗаказа --> ЗаказОформлен : Заказ оформлен
  ЗаказОформлен --> Ожидание : Вернуться к покупкам
}

@enduml
