@startuml
scale 1150 width

[*] --> НеАвторизован

state НеАвторизован {
  [*] --> Ожидание
  Ожидание --> Регистрация : Кликнул на "Зарегистрироваться"
  Регистрация --> Ожидание : Регистрация не удалась
  Регистрация --> Авторизован : Регистрация успешна
  Авторизован --> НеАвторизован : Выход
}

state Авторизован {
  [*] --> Активный
  Активный --> ДобавлениеВКорзину : Добавить в корзину
}

state ДобавлениеВКорзину {
  [*] --> Активный
  Активный --> ОформлениеЗаказа : Перейти к оформлению заказа
}

state ОформлениеЗаказа {
  [*] --> Активный
  Активный --> ЗаказОформлен : Заказ размещен успешно
  Активный --> ДобавлениеВКорзину : Отменить оформление заказа
}

state ЗаказОформлен {
  [*] --> Активный
  Активный --> ДобавлениеВКорзину : Вернуться к покупкам
}

@enduml
