@startuml
scale 750 width

[*] --> НеАвторизован

state НеАвторизован {
  [*] --> Ожидание
  Ожидание --> Авторизация : Кликнул на "SignIn"
  Авторизация --> Авторизован : Пользователь аутентифицирован
  Авторизация --> Ожидание : Неудачная авторизация
  Авторизован --> ДобавлениеВКорзину : Добавить в корзину
}

state ДобавлениеВКорзину {
  [*] --> Активный
  Активный --> ОформлениеЗаказа : Перейти к оформлению заказа
}

state ОформлениеЗаказа {
  [*] --> Активный
  Активный --> ЗаказРазмещен : Заказ размещен успешно
  Активный --> ДобавлениеВКорзину : Отменить оформление заказа
}

state ЗаказРазмещен {
  [*] --> Активный
  Активный --> ДобавлениеВКорзину : Вернуться к покупкам
}

@enduml
